from chessPlayer_tree import *
from chessPlayer_analyzer import *
from chess import *

a = tree(100)
b = tree(25)
c = tree(50)
d = tree(73)
e = tree(80)
f = tree(81)
g = tree(89)
h = tree(21)
i = tree(43)
j = tree(23)
k = tree(-40)
l = tree(54)
m = tree(78)
n = tree(60)
b.AddSuccessor(e)
b.AddSuccessor(f)
b.AddSuccessor(g)
b.AddSuccessor(h)
b.AddSuccessor(i)
c.AddSuccessor(j)
c.AddSuccessor(k)
c.AddSuccessor(l)
c.AddSuccessor(m)
c.AddSuccessor(n)
a.AddSuccessor(b)
a.AddSuccessor(c)
#a.Print_DepthFirst()
#print(alphabeta(a,2,-1000000,1000000,True))

cBoard = generateBoard() 
print(chessPlayer(cBoard,10)[1])
#printBoard(cBoard)
#ret=generateGameTree(a,cBoard,10,3)
#printBoard(cBoard)
#print(cBoard)
#print(type(ret))
#ret.Print_DepthFirst()
